name: Okuna
description: Social Network

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+99

environment:
  sdk: ">=2.1.0 <3.0.0"

publish_to: none

dependencies:
  exif: ^1.0.2
  html: ^0.14.0+2
  expandable: ^4.1.4
  uuid: ^2.0.1
  flutter_image_compress: ^0.7.0
  inview_notifier_list:
    git:
      url: https://github.com/OkunaOrg/inview_notifier_list.git
      ref: d60972d4928463352781e027f20bd5eca0007cd9
  connectivity: ^0.4.4
  visibility_detector: ^0.1.5
  http_retry: ^0.1.1+3
  video_thumbnail: ^0.2.5+1
  flutter_ffmpeg: ^0.3.0
  open_iconic_flutter: ^0.3.0
  retry: ^3.0.0+1
  shared_preferences: ^0.5.2
  flutter_markdown: ^0.2.0
  file_picker: ^2.1.5+1
  sentry_flutter: ^4.0.1
  screen: ^0.0.5
  back_button_interceptor: ^4.0.1
  flutter_colorpicker: any
  intercom_flutter: ^2.3.3
  device_info: ^0.4.0+1
  flutter_pagewise: ^1.2.2
  tinycolor: ^1.0.2
  onesignal_flutter: ^2.6.2
  flutter_advanced_networkimage:
    git:
      url: https://github.com/OkunaOrg/flutter_advanced_networkimage.git
      ref: bugfix/fix-breaking-master-change
  dcache: ^0.1.0
  validators: ^1.0.0+1
  url_launcher: ^5.7.10
  uni_links: ^0.2.0
  flutter_slidable: "^0.5.7"
  flutter_cache_manager: ^1.4.1
  cached_network_image: ^2.2.0+1
  timeago: ^2.0.9
  public_suffix: ^1.2.0
  pigment: ^1.0.3
  photo_view: ^0.9.2
  flutter_svg: 0.18.0
  flutter_secure_storage: ^3.1.2
  mime: ^0.9.6+2
  http: ^0.12.0
  throttling: ^0.8.0
  wakelock: ^0.1.3
  rxdart: ^0.24.1
  video_player:
    git:
      url: https://github.com/OkunaOrg/plugins.git
      ref: ricardo/develop2
      path: packages/video_player
  sprintf: "^4.0.0"
  image_picker: 0.6.7+21
  image_cropper: ^1.3.1
  shimmer: ^1.0.0
  share: ^0.6.4
  path: ^1.7.0
  package_info: ^0.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  intl_translation: ^0.17.10+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/images/icon-adaptive-foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/theme-previews/theme-preview-dark.png
    - assets/images/theme-previews/theme-preview-colorful.png
    - assets/images/theme-previews/theme-preview-dark-gold.png
    - assets/images/theme-previews/theme-preview-white.png
    - assets/images/theme-previews/theme-preview-white-gold.png
    - assets/images/theme-previews/theme-preview-space-blue.png
    - assets/images/theme-previews/theme-preview-light-blue.png
    - assets/images/theme-previews/theme-preview-light-rose.png
    - assets/images/theme-previews/theme-preview-space-rose.png
    - assets/images/theme-previews/theme-preview-light-cinnabar.png
    - assets/images/theme-previews/theme-preview-space-cinnabar.png
    - assets/images/theme-previews/theme-preview-light-royale.png
    - assets/images/theme-previews/theme-preview-space-royale.png
    - assets/images/splash-background.png
    - assets/images/openbook-o-logo.png
    - assets/images/pixel-universe.jpg
    - assets/images/confetti-background.gif
    - assets/images/icons/gif-icon.png
    - assets/images/icons/profile-icon.png
    - assets/images/icons/connections-icon.png
    - assets/images/icons/burner-icon.png
    - assets/images/icons/settings-icon.png
    - assets/images/icons/help-icon.png
    - assets/images/icons/thinking.gif
    - assets/images/icons/customize-icon.png
    - assets/images/icons/logout-icon.png
    - assets/images/icons/audience-icon.png
    - assets/images/icons/home-icon.png
    - assets/images/icons/notifications-icon.png
    - assets/images/icons/search-icon.png
    - assets/images/icons/communities-icon.png
    - assets/images/icons/create-post-icon.png
    - assets/images/icons/chat-icon.png
    - assets/images/icons/photo-icon.png
    - assets/images/icons/video-icon.png
    - assets/images/icons/camera-icon.png
    - assets/images/icons/warning-icon.png
    - assets/images/icons/success-icon.png
    - assets/images/icons/error-icon.png
    - assets/images/icons/info-icon.png
    - assets/images/icons/comments-icon.png
    - assets/images/icons/comment-icon.png
    - assets/images/icons/react-icon.png
    - assets/images/icons/like-icon.png
    - assets/images/icons/finish-icon.png
    - assets/images/icons/finish-icon.png
    - assets/images/icons/expand-icon.png
    - assets/images/icons/load-more-posts-icon.gif
    - assets/images/stickers/female-instructor.png
    - assets/images/stickers/got-it.png
    - assets/images/stickers/owl-instructor.png
    - assets/images/stickers/perplexed-owl.png
    - assets/images/categories/category_all-min.png
    - assets/images/fallbacks/post-fallback.png
    - assets/images/fallbacks/cover-fallback.jpg
    - assets/images/fallbacks/avatar-fallback.jpg
    - assets/other/public_suffix_list.dat
    - .env.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          style: normal
        - asset: assets/fonts/NunitoSans-Bold.ttf
          style: italic
    - family: VisbyRoundCF
      fonts:
        - asset: assets/fonts/VisbyRoundCF-Regular.otf
          style: normal
        - asset: assets/fonts/VisbyRoundCF-Bold.otf
          style: italic
    - family: CogogooseProSemilight
      fonts:
        - asset: assets/fonts/Cocogoose-Pro-Semilight.ttf
          style: normal
    - family: ""
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
